# Phase 5: SQL Analytics

## Objective

SQL is used to analyze structured business data efficiently.

In this notebook, we will:

- Import the cleaned dataset into SQLite
- Execute SQL queries
- Analyze sales, profit, customers, and regions
- Compare SQL analysis with Python analysis

### Tools Used

- SQLite
- SQL
- Python
- Pandas

In [1]:
import pandas as pd
import sqlite3

print("Libraries Loaded Successfully!")

Libraries Loaded Successfully!

## Load the Cleaned Dataset

Load the cleaned CSV file created during the Data Cleaning phase.

In [2]:
df = pd.read_csv("../data/cleaned_superstore.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

## Create SQLite Database

Create a local SQLite database and import the dataset into a table named `orders`.

In [3]:
conn = sqlite3.connect("ecommerce.db")

df.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

print("Database Created Successfully!")

Database Created Successfully!

## Query 1 – Total Sales

In [4]:
query = """
SELECT
ROUND(SUM(Sales),2) AS Total_Sales
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Sales
0   2326534.35

## Query 2 – Total Profit

In [5]:
query = """
SELECT
ROUND(SUM(Profit),2) AS Total_Profit
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Profit
0     292296.81

## Query 3 – Sales by Category

In [6]:
query = """
SELECT
Category,
ROUND(SUM(Sales),2) AS Sales
FROM orders
GROUP BY Category
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

          Category      Sales
0       Technology  839893.28
1        Furniture  754747.76
2  Office Supplies  731893.31

## Query 4 – Sales by Region

In [7]:
query = """
SELECT
Region,
ROUND(SUM(Sales),2) AS Sales
FROM orders
GROUP BY Region
ORDER BY Sales DESC;
"""

pd.read_sql(query, conn)

    Region      Sales
0     West  739813.61
1     East  691828.17
2  Central  503170.67
3    South  391721.91

## Query 5 – Top 10 Customers

In [8]:
query = """
SELECT
`Customer Name`,
ROUND(SUM(Sales),2) AS Total_Sales
FROM orders
GROUP BY `Customer Name`
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name  Total_Sales
0         Sean Miller     25043.05
1        Tamara Chand     19052.22
2        Raymond Buch     15117.34
3        Tom Ashbrook     14595.62
4       Adrian Barton     14473.57
5        Ken Lonsdale     14175.23
6        Sanjit Chand     14142.33
7        Hunter Lopez     12873.30
8        Sanjit Engle     12209.44
9  Christopher Conant     12129.07

## Query 6 – Top 10 Products

In [9]:
query = """
SELECT
`Product Name`,
ROUND(SUM(Sales),2) AS Sales
FROM orders
GROUP BY `Product Name`
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name     Sales
0              Canon imageCLASS 2200 Advanced Copier  61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.38
2  Cisco TelePresence System EX90 Videoconferenci...  22638.48
3       HON 5400 Series Task Chairs for Big and Tall  21870.58
4         GBC DocuBind TL300 Electric Binding System  19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System  19024.50
6               Hewlett Packard LaserJet 3310 Copier  18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...  18374.90
8          GBC DocuBind P400 Electric Binding System  17965.07
9        High Speed Automatic Electric Letter Opener  17030.31

## Close Database Connection

Always close the database connection after completing SQL operations.

In [10]:
conn.close()

print("Database Connection Closed!")

Database Connection Closed!